set(EBBACKUP_SQLITE_MASTER_DIR "${CMAKE_CURRENT_LIST_DIR}/../../sqlite-master" CACHE PATH
    "Path to sqlite-master source tree")
set(EBBACKUP_SQLITE3_C "${EBBACKUP_SQLITE_MASTER_DIR}/sqlite3.c")
set(EBBACKUP_SQLITE3_H "${EBBACKUP_SQLITE_MASTER_DIR}/sqlite3.h")
set(EBBACKUP_SQLITE_AMAL_DIR "${CMAKE_CURRENT_BINARY_DIR}/sqlite_amalgamation")
set(EBBACKUP_SQLITE_DL_C "${EBBACKUP_SQLITE_AMAL_DIR}/sqlite3.c")
set(EBBACKUP_SQLITE_DL_H "${EBBACKUP_SQLITE_AMAL_DIR}/sqlite3.h")

function(ebbackup_try_generate_sqlite_amalgamation)
  if(EXISTS "${EBBACKUP_SQLITE3_C}" AND EXISTS "${EBBACKUP_SQLITE3_H}")
    return()
  endif()
  if(NOT EXISTS "${EBBACKUP_SQLITE_MASTER_DIR}/Makefile.msc")
    return()
  endif()
  message(STATUS "Generating SQLite amalgamation in ${EBBACKUP_SQLITE_MASTER_DIR}")
  if(WIN32)
    execute_process(
      COMMAND cmd /c "nmake /f Makefile.msc sqlite3.c"
      WORKING_DIRECTORY "${EBBACKUP_SQLITE_MASTER_DIR}"
      RESULT_VARIABLE _sqlite_gen_rc
      ERROR_VARIABLE _sqlite_gen_err)
  else()
    execute_process(
      COMMAND make sqlite3.c
      WORKING_DIRECTORY "${EBBACKUP_SQLITE_MASTER_DIR}"
      RESULT_VARIABLE _sqlite_gen_rc
      ERROR_VARIABLE _sqlite_gen_err)
  endif()
  if(NOT _sqlite_gen_rc EQUAL 0 OR NOT EXISTS "${EBBACKUP_SQLITE3_C}")
    message(STATUS "SQLite nmake/make generation failed; will try download fallback")
  endif()
endfunction()

function(ebbackup_download_sqlite_amalgamation)
  if(EXISTS "${EBBACKUP_SQLITE_DL_C}" AND EXISTS "${EBBACKUP_SQLITE_DL_H}")
    return()
  endif()
  file(MAKE_DIRECTORY "${EBBACKUP_SQLITE_AMAL_DIR}")
  set(_zip "${EBBACKUP_SQLITE_AMAL_DIR}/sqlite-amalgamation.zip")
  set(_url "https://www.sqlite.org/2024/sqlite-amalgamation-3460100.zip")
  message(STATUS "Downloading SQLite amalgamation from ${_url}")
  file(DOWNLOAD "${_url}" "${_zip}" STATUS _dl_status TIMEOUT 120)
  list(GET _dl_status 0 _dl_rc)
  if(NOT _dl_rc EQUAL 0)
    message(WARNING "SQLite amalgamation download failed (rc=${_dl_rc})")
    return()
  endif()
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E tar xzf "${_zip}"
    WORKING_DIRECTORY "${EBBACKUP_SQLITE_AMAL_DIR}"
    RESULT_VARIABLE _tar_rc)
  if(_tar_rc EQUAL 0)
    file(GLOB _extracted_c "${EBBACKUP_SQLITE_AMAL_DIR}/*/sqlite3.c")
    file(GLOB _extracted_h "${EBBACKUP_SQLITE_AMAL_DIR}/*/sqlite3.h")
    if(_extracted_c AND _extracted_h)
      file(COPY "${_extracted_c}" DESTINATION "${EBBACKUP_SQLITE_AMAL_DIR}")
      file(COPY "${_extracted_h}" DESTINATION "${EBBACKUP_SQLITE_AMAL_DIR}")
    endif()
  endif()
  if(NOT _tar_rc EQUAL 0 OR NOT EXISTS "${EBBACKUP_SQLITE_DL_C}")
    message(WARNING "SQLite amalgamation extract failed")
    return()
  endif()
endfunction()

ebbackup_try_generate_sqlite_amalgamation()
if(NOT EXISTS "${EBBACKUP_SQLITE3_C}")
  ebbackup_download_sqlite_amalgamation()
endif()

if(EXISTS "${EBBACKUP_SQLITE3_C}")
  set(_SQLITE3_SRC "${EBBACKUP_SQLITE3_C}")
  set(_SQLITE3_INC "${EBBACKUP_SQLITE_MASTER_DIR}")
elseif(EXISTS "${EBBACKUP_SQLITE_DL_C}")
  set(_SQLITE3_SRC "${EBBACKUP_SQLITE_DL_C}")
  set(_SQLITE3_INC "${EBBACKUP_SQLITE_AMAL_DIR}")
else()
  set(_SQLITE3_SRC "")
endif()

if(_SQLITE3_SRC)
  add_library(ebbackup_sqlite3 STATIC "${_SQLITE3_SRC}")
  target_include_directories(ebbackup_sqlite3 PUBLIC "${_SQLITE3_INC}")
  target_compile_definitions(ebbackup_sqlite3 PUBLIC EBBACKUP_HAVE_SQLITE3)
  if(MSVC)
    target_compile_options(ebbackup_sqlite3 PRIVATE /W0)
  else()
    target_compile_options(ebbackup_sqlite3 PRIVATE -w)
  endif()
  set(EBBACKUP_HAVE_SQLITE3 TRUE)
else()
  set(EBBACKUP_HAVE_SQLITE3 FALSE)
  message(WARNING "SQLite unavailable; sqlite_checkpoint plugin will be limited")
endif()
